sudo: required

services:
    - docker

before_install:
    - cp .env.test.dist .env
    - docker-compose up -d
    - docker-compose exec web composer install --no-interaction
    - docker-compose exec web php bin/console doctrine:schema:update --force

script:
    - docker-compose exec web php bin/console doctrine:schema:validate --skip-sync
    - docker-compose exec web php bin/console about
    - docker-compose exec web vendor/bin/phpunit
