language: php

php:
  - 7.1
  - 7.2
  - nightly

matrix:
    allow_failures:
      - php: nightly

env:
    - APP_ENV=test

before_script:
    - echo 'date.timezone = "UTC"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
    - composer install --no-interaction
    - php bin/phpunit --coverage-clover build/coverage/xml

after_script:
    - php vendor/bin/codacycoverage clover build/coverage/xml
