# app/config/routing.yml
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

home:
    path:     /
    defaults: { _controller: AppBundle:Home:index }

admin:
    path:     /admin
    defaults: { _controller: AppBundle:Admin:index }

profile:
    path:     /profile
    defaults: { _controller: AppBundle:Security:profile }

google_login:
    path: /login/check-google

logout:
    path: /logout
