index:
    path: /
    controller: App\Controller\DefaultController::index

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

google_login:
    path: /login/check-google

admin:
    path: /admin
    controller: App\Controller\AdminController::index

login:
    path: /login

profile:
    path: /profile
    controller: App\Controller\ProfileController::index

logout:
    path: /logout

#twitter:
#    path: /twitter
#    controller: App\Controller\TwitterController::index
